using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using LogicLayer;
using DataObjects;

namespace PresentationLayer
{
    /// <summary>
    /// Interaction logic for cntrlScheduleControl.xaml
    /// </summary>
     
    // This class is used to show the schedule of a user that is either a volunteer or employee.
    public partial class cntrlScheduleControl : UserControl
    {

        IScheduleManager _scheduleManager;
        User _user;
        PersonScheduleVM _schedule;
        List<PersonScheduleVM> _schedules;

        // This is the constructor for this class. It only needs a user in order to work correctly
        public cntrlScheduleControl(User user)
        {
            InitializeComponent();
            _user = user;
            _scheduleManager = new ScheduleManager();
            
            refreshScheduleList();
        }

        // this method refreshes the schedule list.
        private void refreshScheduleList()
        {
            _schedules = _scheduleManager.RetrieveSchedule(_user.PersonID);
            dgSchedule.ItemsSource = _schedules;
        }

        // This event handler fires when the columns in the dgSchedule data grid are automaticallt generated. It formats
        // The data grid in sucha way that is more human readable.
        private void DgSchedule_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgSchedule.Columns.Remove(dgSchedule.Columns[16]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[15]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[14]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[13]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[12]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[11]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[10]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[9]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[8]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[7]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[6]);
            
            dgSchedule.Columns.Remove(dgSchedule.Columns[3]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[2]);
            dgSchedule.Columns.Remove(dgSchedule.Columns[1]);
            

            dgSchedule.Columns[0].Header = "Activity Name";
            dgSchedule.Columns[1].Header = "Start Time";
            dgSchedule.Columns[2].Header = "End Time";
        }


        // This event handler fires when the selected item in the dgSchedule data grid is changed. It then
        // populates the various text boxes with their respective information.
        private void DgSchedule_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            _schedule = (PersonScheduleVM)dgSchedule.SelectedItem;
            txtActivityName.Text = _schedule.ActivityName;
            txtScheduleType.Text = _schedule.Type;
            txtStartTime.Text = _schedule.Start.ToShortDateString() + _schedule.Start.ToShortTimeString();
            txtEndTime.Text = _schedule.End.ToShortDateString() + _schedule.End.ToShortTimeString();
            txtActivityType.Text = _schedule.ActivityTypeID;
            txtAddress1.Text = _schedule.Address1;
            txtAddress2.Text = _schedule.Address2;
            txtCity.Text = _schedule.City;
            txtLocationName.Text = _schedule.LocationName;
            txtState.Text = _schedule.State;
            txtZip.Text = _schedule.Zip;
            txtFirstName.Text = _schedule.FirstName;
            txtLastName.Text = _schedule.LastName;
            txtDescription.Text = _schedule.Description;
        }
    }
}
